from fastapi import FastAPI
from starlette.responses import Response

from views import api_router

app = FastAPI(
    title="Items Api",
    description="API Generated by Median Code",
    version="0.1.0",
)
app.include_router(api_router)