from typing import Optional

from pydantic import BaseModel, Field, field_validator, model_validator

from api_craft.models.types import PascalCaseName
from api_craft.models.validators import validate_model_field_types, validate_view_references


class InputField(BaseModel):
    """Field definition for an input object.

    :ivar type: Declared field type, supporting primitive values and object references.
    :ivar name: Field identifier within the object.
    :ivar required: Flag indicating whether the field must be provided.
    """

    type: str
    name: str
    required: bool = False


class InputModel(BaseModel):
    """Shared object definition with a name and typed fields.

    :ivar name: Object name in PascalCase.
    :ivar fields: Ordered collection of :class:`InputField` definitions.
    """

    name: PascalCaseName
    fields: list[InputField]


class InputQueryParam(BaseModel):
    """Query parameter definition for a view.

    :ivar name: Snake_case identifier exposed to consumers.
    :ivar type: Declared type string compatible with FastAPI annotations.
    :ivar required: Flag indicating whether the parameter is mandatory.
    """

    name: str
    type: str
    required: bool = False


class InputPathParam(BaseModel):
    """Path parameter definition for a view.

    :ivar name: Snake_case identifier extracted from the route.
    :ivar type: Declared type string for the parameter value.
    """

    name: str
    type: str


class InputView(BaseModel):
    """HTTP endpoint definition referencing shared request and response objects.

    :ivar name: Explicit operation name used in generated code.
    :ivar path: Route pattern compatible with FastAPI routing.
    :ivar method: HTTP verb for the view.
    :ivar tag: Optional OpenAPI tag for documentation grouping.
    :ivar response: Name of the response object referenced by the view.
    :ivar request: Name of the request object referenced by the view.
    :ivar query_params: Optional query parameter definitions scoped to the view.
    :ivar path_params: Optional path parameter definitions scoped to the view.
    """

    name: PascalCaseName
    path: str
    method: str
    tag: str | None = None
    response: PascalCaseName | None = None
    request: PascalCaseName | None = None
    query_params: list[InputQueryParam] | None = None
    path_params: list[InputPathParam] | None = None

    @field_validator("response", "request", mode="before")
    @classmethod
    def _strip_reference(cls, value: str | None) -> str | None:
        """Strip whitespace from reference identifiers.

        :param value: Raw field value provided by the caller.
        :returns: Normalised reference name or ``None`` when the value is empty.
        """

        if value is None:
            return None

        stripped = value.strip()
        return stripped or None


class InputApiConfig(BaseModel):
    """Configuration flags for the generated API.

    :ivar healthcheck: Optional path used to expose a healthcheck route.
    :ivar response_placeholders: Toggle for generating placeholder response bodies.
    """

    healthcheck: Optional[str] = None
    response_placeholders: bool = False


class InputAPI(BaseModel):
    """Root model describing the API to generate.

    :ivar name: API identifier used for project structure.
    :ivar version: Semantic version string.
    :ivar author: Author metadata for packaging.
    :ivar description: Human-readable API overview.
    :ivar objects: Shared object definitions referenced across views.
    :ivar views: HTTP endpoints composing the API.
    :ivar config: Additional configuration for generation behavior.
    """

    name: PascalCaseName
    version: str = "0.1.0"
    author: str = "Median Code"
    description: str = "API Generated by Median Code"
    objects: list[InputModel] = Field(default_factory=list)
    views: list[InputView]
    config: InputApiConfig = InputApiConfig()

    @model_validator(mode="after")
    def _validate_references(cls, model: "InputAPI") -> "InputAPI":
        """Validate cross-object references after the model is instantiated.

        :param model: Instance created by Pydantic prior to validation.
        :returns: The validated model instance.
        :raises ValueError: If any reference points to an unknown object.
        """

        declared_object_names = {obj.name for obj in model.objects}
        validate_model_field_types(model.objects, declared_object_names)
        validate_view_references(model.views, declared_object_names)
        return model
