from typing import Optional

from pydantic import BaseModel, Field


class InputField(BaseModel):
    """Field definition for an input object.

    :ivar type: Declared field type, supporting primitive values and object references.
    :ivar name: Field identifier within the object.
    :ivar required: Flag indicating whether the field must be provided.
    """

    type: str
    name: str
    required: bool = False


class InputModel(BaseModel):
    """Shared object definition with a name and typed fields.

    :ivar name: Object name in PascalCase.
    :ivar fields: Ordered collection of :class:`InputField` definitions.
    """

    name: str
    fields: list[InputField]


class InputQueryParam(BaseModel):
    """Query parameter definition for a view.

    :ivar name: Snake_case identifier exposed to consumers.
    :ivar type: Declared type string compatible with FastAPI annotations.
    :ivar required: Flag indicating whether the parameter is mandatory.
    """

    name: str
    type: str
    required: bool = False


class InputPathParam(BaseModel):
    """Path parameter definition for a view.

    :ivar name: Snake_case identifier extracted from the route.
    :ivar type: Declared type string for the parameter value.
    """

    name: str
    type: str


class InputView(BaseModel):
    """HTTP endpoint definition referencing shared request and response objects.

    :ivar name: Optional explicit operation name used in generated code.
    :ivar path: Route pattern compatible with FastAPI routing.
    :ivar method: HTTP verb for the view.
    :ivar tag: Optional OpenAPI tag for documentation grouping.
    :ivar response: Name of the response object referenced by the view.
    :ivar request: Name of the request object referenced by the view.
    :ivar query_params: Optional query parameter definitions scoped to the view.
    :ivar path_params: Optional path parameter definitions scoped to the view.
    """

    name: str | None = None
    path: str
    method: str
    tag: str | None = None
    response: str | None = None
    request: str | None = None
    query_params: list[InputQueryParam] | None = None
    path_params: list[InputPathParam] | None = None


class InputApiConfig(BaseModel):
    """Configuration flags for the generated API.

    :ivar healthcheck: Optional path used to expose a healthcheck route.
    :ivar response_placeholders: Toggle for generating placeholder response bodies.
    """

    healthcheck: Optional[str] = None
    response_placeholders: bool = False


class InputAPI(BaseModel):
    """Root model describing the API to generate.

    :ivar name: API identifier used for project structure.
    :ivar version: Semantic version string.
    :ivar author: Author metadata for packaging.
    :ivar description: Human-readable API overview.
    :ivar objects: Shared object definitions referenced across views.
    :ivar views: HTTP endpoints composing the API.
    :ivar config: Additional configuration for generation behavior.
    """

    name: str
    version: str = "0.1.0"
    author: str = "Median Code"
    description: str = "API Generated by Median Code"
    objects: list[InputModel] = Field(default_factory=list)
    views: list[InputView]
    config: InputApiConfig = InputApiConfig()
