"""Initial schema

Revision ID: 4141ad7f2255
Revises: 
Create Date: 2026-02-05 00:21:53.575168
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4141ad7f2255'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('namespaces',
    sa.Column('id', sa.String(length=255), nullable=False),
    sa.Column('user_id', sa.String(length=255), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('locked', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_namespaces_user_id'), 'namespaces', ['user_id'], unique=False)
    op.create_table('apis',
    sa.Column('id', sa.String(length=255), nullable=False),
    sa.Column('namespace_id', sa.String(length=255), nullable=False),
    sa.Column('user_id', sa.String(length=255), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('version', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('base_url', sa.String(length=255), nullable=False),
    sa.Column('server_url', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['namespace_id'], ['namespaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_apis_namespace_id'), 'apis', ['namespace_id'], unique=False)
    op.create_index(op.f('ix_apis_user_id'), 'apis', ['user_id'], unique=False)
    op.create_table('fields',
    sa.Column('id', sa.String(length=255), nullable=False),
    sa.Column('namespace_id', sa.String(length=255), nullable=False),
    sa.Column('user_id', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('default_value', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['namespace_id'], ['namespaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fields_namespace_id'), 'fields', ['namespace_id'], unique=False)
    op.create_index(op.f('ix_fields_user_id'), 'fields', ['user_id'], unique=False)
    op.create_table('objects',
    sa.Column('id', sa.String(length=255), nullable=False),
    sa.Column('namespace_id', sa.String(length=255), nullable=False),
    sa.Column('user_id', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['namespace_id'], ['namespaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_objects_namespace_id'), 'objects', ['namespace_id'], unique=False)
    op.create_index(op.f('ix_objects_user_id'), 'objects', ['user_id'], unique=False)
    op.create_table('endpoint_tags',
    sa.Column('id', sa.String(length=255), nullable=False),
    sa.Column('namespace_id', sa.String(length=255), nullable=False),
    sa.Column('api_id', sa.String(length=255), nullable=False),
    sa.Column('user_id', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['api_id'], ['apis.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['namespace_id'], ['namespaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_endpoint_tags_api_id'), 'endpoint_tags', ['api_id'], unique=False)
    op.create_index(op.f('ix_endpoint_tags_namespace_id'), 'endpoint_tags', ['namespace_id'], unique=False)
    op.create_index(op.f('ix_endpoint_tags_user_id'), 'endpoint_tags', ['user_id'], unique=False)
    op.create_table('field_validators',
    sa.Column('id', sa.String(length=255), nullable=False),
    sa.Column('field_id', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('params', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['field_id'], ['fields.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_field_validators_field_id'), 'field_validators', ['field_id'], unique=False)
    op.create_table('object_field_associations',
    sa.Column('id', sa.String(length=255), nullable=False),
    sa.Column('object_id', sa.String(length=255), nullable=False),
    sa.Column('field_id', sa.String(length=255), nullable=False),
    sa.Column('required', sa.Boolean(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['field_id'], ['fields.id'], ),
    sa.ForeignKeyConstraint(['object_id'], ['objects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_object_field_associations_field_id'), 'object_field_associations', ['field_id'], unique=False)
    op.create_index(op.f('ix_object_field_associations_object_id'), 'object_field_associations', ['object_id'], unique=False)
    op.create_table('api_endpoints',
    sa.Column('id', sa.String(length=255), nullable=False),
    sa.Column('namespace_id', sa.String(length=255), nullable=False),
    sa.Column('api_id', sa.String(length=255), nullable=False),
    sa.Column('user_id', sa.String(length=255), nullable=False),
    sa.Column('method', sa.Enum('GET', 'POST', 'PUT', 'PATCH', 'DELETE', name='http_method'), nullable=False),
    sa.Column('path', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('tag_id', sa.String(length=255), nullable=True),
    sa.Column('query_params_object_id', sa.String(length=255), nullable=True),
    sa.Column('request_body_object_id', sa.String(length=255), nullable=True),
    sa.Column('response_body_object_id', sa.String(length=255), nullable=True),
    sa.Column('use_envelope', sa.Boolean(), nullable=False),
    sa.Column('response_shape', sa.Enum('object', 'list', name='response_shape'), nullable=False),
    sa.ForeignKeyConstraint(['api_id'], ['apis.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['namespace_id'], ['namespaces.id'], ),
    sa.ForeignKeyConstraint(['query_params_object_id'], ['objects.id'], ),
    sa.ForeignKeyConstraint(['request_body_object_id'], ['objects.id'], ),
    sa.ForeignKeyConstraint(['response_body_object_id'], ['objects.id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['endpoint_tags.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_api_endpoints_api_id'), 'api_endpoints', ['api_id'], unique=False)
    op.create_index(op.f('ix_api_endpoints_namespace_id'), 'api_endpoints', ['namespace_id'], unique=False)
    op.create_index(op.f('ix_api_endpoints_tag_id'), 'api_endpoints', ['tag_id'], unique=False)
    op.create_index(op.f('ix_api_endpoints_user_id'), 'api_endpoints', ['user_id'], unique=False)
    op.create_table('endpoint_parameters',
    sa.Column('id', sa.String(length=255), nullable=False),
    sa.Column('endpoint_id', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('required', sa.Boolean(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['endpoint_id'], ['api_endpoints.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_endpoint_parameters_endpoint_id'), 'endpoint_parameters', ['endpoint_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_endpoint_parameters_endpoint_id'), table_name='endpoint_parameters')
    op.drop_table('endpoint_parameters')
    op.drop_index(op.f('ix_api_endpoints_user_id'), table_name='api_endpoints')
    op.drop_index(op.f('ix_api_endpoints_tag_id'), table_name='api_endpoints')
    op.drop_index(op.f('ix_api_endpoints_namespace_id'), table_name='api_endpoints')
    op.drop_index(op.f('ix_api_endpoints_api_id'), table_name='api_endpoints')
    op.drop_table('api_endpoints')
    op.drop_index(op.f('ix_object_field_associations_object_id'), table_name='object_field_associations')
    op.drop_index(op.f('ix_object_field_associations_field_id'), table_name='object_field_associations')
    op.drop_table('object_field_associations')
    op.drop_index(op.f('ix_field_validators_field_id'), table_name='field_validators')
    op.drop_table('field_validators')
    op.drop_index(op.f('ix_endpoint_tags_user_id'), table_name='endpoint_tags')
    op.drop_index(op.f('ix_endpoint_tags_namespace_id'), table_name='endpoint_tags')
    op.drop_index(op.f('ix_endpoint_tags_api_id'), table_name='endpoint_tags')
    op.drop_table('endpoint_tags')
    op.drop_index(op.f('ix_objects_user_id'), table_name='objects')
    op.drop_index(op.f('ix_objects_namespace_id'), table_name='objects')
    op.drop_table('objects')
    op.drop_index(op.f('ix_fields_user_id'), table_name='fields')
    op.drop_index(op.f('ix_fields_namespace_id'), table_name='fields')
    op.drop_table('fields')
    op.drop_index(op.f('ix_apis_user_id'), table_name='apis')
    op.drop_index(op.f('ix_apis_namespace_id'), table_name='apis')
    op.drop_table('apis')
    op.drop_index(op.f('ix_namespaces_user_id'), table_name='namespaces')
    op.drop_table('namespaces')
    # ### end Alembic commands ###
