{#- Parameters: -#}
{#- api : TemplateApi -#}
# Use an official lightweight Python image.
# https://hub.docker.com/_/python
FROM python:3.13-slim
LABEL org.opencontainers.image.title="{{ api.snake_name }}"

# Set the working directory in the container
WORKDIR /app

# Install any dependencies
COPY src/requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

COPY src/ .

# Specify the command to run on container start
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "80"]