from typing import List

from pydantic import BaseModel


class InputField(BaseModel):
    type: str
    name: str
    required: bool = False


class InputModel(BaseModel):
    name: str
    fields: list[InputField]


class InputQueryParam(BaseModel):
    name: str
    type: str
    required: bool = False


class InputPathParam(BaseModel):
    name: str
    type: str


class InputView(BaseModel):
    name: str
    path: str
    method: str
    tag: str = None
    response: InputModel
    request: InputModel = None
    query_params: List[InputQueryParam] = None
    path_params: List[InputPathParam] = None


class InputAPI(BaseModel):
    name: str
    version: str = "0.1.0"
    author: str = "Median Code"
    description: str = "API Generated by Median Code"
    views: List[InputView]
